/**
 * The build script's preset reader must agree with the engine's parser.
 *
 * `data/soundfontManifest.json` is generated by `scripts/build-soundfont-manifest.mjs`,
 * which has its own minimal `phdr` reader — it runs before any TypeScript is
 * compiled, so it cannot import `SoundFontParser`.
 *
 * That duplication is only safe while the two agree about **ordering**.
 * `Track.soundFont.presetIndex` is a raw index into the preset array and is
 * stored inside saved projects. If the manifest numbered presets differently
 * from the parser that actually plays them, every instrument in every saved
 * project would quietly become a different sound — with nothing failing.
 *
 * Synthetic fonts, so this runs in CI without the 30 MB bank on disk.
 */

import { SoundFontParser, GenOper } from '@/engine/instruments/soundfont/SoundFontParser';
import { extractPresets, findPdtaChunk } from '@/scripts/sf2Presets.cjs';
import { buildSf2, range, type FontSpec } from '@/tests/fixtures/sf2Builder';

/** What the engine's parser reports, in the manifest's shape. */
function viaParser(buffer: ArrayBuffer) {
    return new SoundFontParser().parse(buffer).presets.map((p, index) => ({
        index,
        name: p.name.trim(),
        bank: p.bank,
        program: p.preset,
    }));
}

/** A font with `names.length` presets, each addressing its own instrument. */
function fontWith(
    presets: { name: string; bank: number; program: number }[],
): ArrayBuffer {
    const spec: FontSpec = {
        presets: presets.map((p, i) => ({
            ...p,
            bags: [{ gens: [[GenOper.instrument, i]] as [number, number][] }],
        })),
        instruments: presets.map((_, i) => ({
            name: `inst${i}`,
            bags: [{
                gens: [
                    [GenOper.keyRange, range(0, 127)],
                    [GenOper.sampleID, i],
                ] as [number, number][],
            }],
        })),
        samples: presets.map((_, i) => ({
            name: `s${i}`, start: i * 100, end: i * 100 + 99, rootKey: 60,
        })),
        sampleCount: presets.length * 100,
    };
    return buildSf2(spec);
}

describe('manifest preset extraction matches SoundFontParser', () => {
    it('agrees on a single-preset font', () => {
        const buffer = fontWith([{ name: 'Grand Piano', bank: 0, program: 0 }]);

        expect(extractPresets(buffer)).toEqual(viaParser(buffer));
    });

    it('agrees on ordering across many presets', () => {
        // Deliberately not in bank/program order: the contract is phdr order,
        // and a sort on either side would break stored presetIndex values.
        const buffer = fontWith([
            { name: 'Strings', bank: 0, program: 48 },
            { name: 'Piano', bank: 0, program: 0 },
            { name: 'Standard Kit', bank: 128, program: 0 },
            { name: 'Bass', bank: 0, program: 33 },
        ]);

        const fromScript = extractPresets(buffer);

        expect(fromScript).toEqual(viaParser(buffer));
        // Pin the order explicitly, so a sort introduced on *both* sides at
        // once would still fail here.
        expect(fromScript.map(p => p.name)).toEqual(
            ['Strings', 'Piano', 'Standard Kit', 'Bass']);
        expect(fromScript.map(p => p.index)).toEqual([0, 1, 2, 3]);
    });

    it('drops the terminal EOP record rather than reporting it as a preset', () => {
        const buffer = fontWith([
            { name: 'One', bank: 0, program: 0 },
            { name: 'Two', bank: 0, program: 1 },
        ]);

        const presets = extractPresets(buffer);

        expect(presets).toHaveLength(2);
        expect(presets.map(p => p.name)).not.toContain('EOP');
    });

    it('reads bank and program from the right offsets', () => {
        // Bank and program are adjacent words; swapping them is the easy
        // mistake, and a drum kit (bank 128) is where it shows up.
        const buffer = fontWith([{ name: 'Standard Kit', bank: 128, program: 7 }]);

        expect(extractPresets(buffer)[0]).toEqual({
            index: 0, name: 'Standard Kit', bank: 128, program: 7,
        });
    });

    it('trims the fixed-width name field', () => {
        const buffer = fontWith([{ name: 'Pad', bank: 0, program: 89 }]);

        // The field is 20 bytes, null-padded — the name must not carry them.
        expect(extractPresets(buffer)[0].name).toBe('Pad');
    });

    it('rejects bytes that are not a SoundFont', () => {
        const notAFont = new Uint8Array(64).buffer;

        expect(() => extractPresets(notAFont)).toThrow(/not a SoundFont/);
    });

    it('finds a pdta subchunk by id', () => {
        const buffer = fontWith([{ name: 'One', bank: 0, program: 0 }]);
        const view = new DataView(buffer);

        expect(findPdtaChunk(view, 'phdr')).not.toBeNull();
        expect(findPdtaChunk(view, 'zzzz')).toBeNull();
    });
});
