export interface PrintOptions {
  title?: string;
  includeTrackNames?: boolean;
  includeMixerSettings?: boolean;
  includePluginSettings?: boolean;
  orientation?: 'portrait' | 'landscape';
  format?: 'a4' | 'letter';
}

export const DEFAULT_PRINT_OPTIONS: PrintOptions = {
  title: 'Project Export',
  includeTrackNames: true,
  includeMixerSettings: true,
  includePluginSettings: false,
  orientation: 'landscape',
  format: 'letter',
};

export function generatePrintContent(
  projectData: any,
  options: PrintOptions = DEFAULT_PRINT_OPTIONS
): string {
  const merged: PrintOptions = { ...DEFAULT_PRINT_OPTIONS, ...options };
  const projectName = projectData?.name || merged.title || 'Unnamed Project';
  const tracks = projectData?.tracks || [];
  const isPortrait = merged.orientation === 'portrait';

  let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(projectName)}</title>
  <style>
    @page { size: ${isPortrait ? 'letter portrait' : 'letter landscape'}; margin: 0.75in; }
    body { font-family: 'SF Mono', 'Consolas', 'Courier New', monospace; font-size: 10pt; color: #222; }
    h1 { font-size: 16pt; margin-bottom: 4pt; }
    .meta { color: #666; font-size: 9pt; margin-bottom: 12pt; }
    .track { margin-bottom: 16pt; page-break-inside: avoid; }
    .track-header { font-weight: bold; font-size: 11pt; border-bottom: 1px solid #ccc; padding-bottom: 2pt; margin-bottom: 6pt; }
    .clip { margin-left: 12pt; margin-bottom: 3pt; font-size: 9pt; display: flex; gap: 8pt; }
    .clip-name { flex: 1; }
    .clip-meta { color: #888; }
    .mixer { margin-top: 6pt; padding: 6pt; background: #f5f5f5; border-radius: 4pt; font-size: 8pt; }
    .mixer-row { display: flex; gap: 8pt; }
    .plugin { margin-left: 12pt; font-size: 8pt; color: #555; }
    .footer { margin-top: 20pt; padding-top: 8pt; border-top: 1px solid #ddd; font-size: 8pt; color: #999; text-align: center; }
    @media print { .no-print { display: none; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(projectName)}</h1>
  <div class="meta">
    Tempo: ${projectData?.tempo || 120} BPM &bull;
    Time: ${projectData?.timeSignature || '4/4'} &bull;
    Key: ${projectData?.keySignature || 'C Maj'} &bull;
    Tracks: ${tracks.length}
  </div>`;

  for (const track of tracks) {
    html += `<div class="track">
      <div class="track-header">
        ${escapeHtml(track.name || 'Untitled')}
        ${options.includeMixerSettings && track.mixer ? `<span style="font-weight:normal;color:#888;margin-left:8pt;">Vol: ${Math.round((track.volume || 0.8) * 100)}% Pan: ${Math.round((track.pan || 0) * 100)}% ${track.muted ? 'MUTED' : ''} ${track.soloed ? 'SOLO' : ''}</span>` : ''}
      </div>`;

    if (track.clips?.length) {
      for (const clip of track.clips) {
        html += `<div class="clip">
          <span class="clip-name">${escapeHtml(clip.name || clip.type || 'Clip')}</span>
          <span class="clip-meta">start: ${clip.start?.toFixed(2) || '0'} &bull; dur: ${clip.duration?.toFixed(2) || '0'}</span>
        </div>`;
      }
    }

    if (options.includeMixerSettings && track.plugins?.length) {
      html += `<div class="mixer"><strong>Plugins:</strong> `;
      for (const plugin of track.plugins) {
        html += `<div class="plugin">${escapeHtml(plugin.name)} (slot ${plugin.slotIndex || 0})</div>`;
      }
      html += `</div>`;
    }

    html += `</div>`;
  }

  html += `<div class="footer">
    Generated by DAW &bull; ${new Date().toLocaleDateString()} &bull; ${tracks.length} tracks
  </div>
  <script>
    window.onload = () => { window.print(); };
  </script>
</body>
</html>`;

  return html;
}

function escapeHtml(text: string): string {
  const map: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' };
  return String(text).replace(/[&<>"']/g, c => map[c] || c);
}
