import { ProjectTemplate } from './types';

export const edmTemplate: ProjectTemplate = {
  id: 'edm',
  name: 'EDM',
  description: 'Energetic electronic dance groove with bass, synths, and FX',
  category: 'Music',
  genre: 'Electronic',
  difficulty: 'Intermediate',
  bpm: 126,
  timeSignature: '4/4',
  keySignature: 'C Major',
  accentColor: '#EC4899',
  previewIcon: '⚡',
  tracks: [
    {
      name: 'Drums',
      type: 'audio',
      color: '#F59E0B',
      volume: 0.9,
      pan: 0,
      muted: false,
      soloed: false,
      icon: 'drum',
      outputBusId: 'stereo-out',
    },
    {
      name: 'Bass',
      type: 'instrument',
      instrument: 'Deep Bass',
      color: '#3B82F6',
      volume: 0.8,
      pan: 0,
      muted: false,
      soloed: false,
      icon: 'guitar',
      outputBusId: 'stereo-out',
    },
    {
      name: 'Synth',
      type: 'instrument',
      instrument: 'Steinway Piano',
      color: '#EC4899',
      volume: 0.7,
      pan: 0,
      muted: false,
      soloed: false,
      icon: 'keyboard',
      outputBusId: 'stereo-out',
    },
    {
      name: 'FX',
      type: 'audio',
      color: '#10B981',
      volume: 0.5,
      pan: 0,
      muted: false,
      soloed: false,
      icon: 'mic',
      outputBusId: 'stereo-out',
    },
  ],
  clips: [
    {
      trackIndex: 0,
      type: 'audio',
      name: 'EDM Drums',
      startBeat: 0,
      duration: 16,
      color: '#F59E0B',
      fileUrl: '/audio/templates/edm/drums.wav',
      loop: true,
    },
    {
      trackIndex: 1,
      type: 'midi',
      name: 'Bassline',
      startBeat: 0,
      duration: 16,
      color: '#3B82F6',
      loop: true,
      notes: [
        // C2 root-fifth pattern (8th notes)
        { pitch: 36, velocity: 90, start: 0, duration: 0.5 },
        { pitch: 43, velocity: 85, start: 0.5, duration: 0.5 },
        { pitch: 36, velocity: 90, start: 1, duration: 0.5 },
        { pitch: 43, velocity: 85, start: 1.5, duration: 0.5 },
        { pitch: 36, velocity: 90, start: 2, duration: 0.5 },
        { pitch: 43, velocity: 85, start: 2.5, duration: 0.5 },
        { pitch: 36, velocity: 90, start: 3, duration: 0.5 },
        { pitch: 43, velocity: 85, start: 3.5, duration: 0.5 },
        // G1 on beat 4
        { pitch: 31, velocity: 88, start: 4, duration: 1 },
        { pitch: 38, velocity: 82, start: 4.5, duration: 0.5 },
        { pitch: 31, velocity: 88, start: 5, duration: 0.5 },
        { pitch: 38, velocity: 82, start: 5.5, duration: 0.5 },
        { pitch: 31, velocity: 88, start: 6, duration: 0.5 },
        { pitch: 38, velocity: 82, start: 6.5, duration: 0.5 },
        { pitch: 31, velocity: 88, start: 7, duration: 0.5 },
        { pitch: 38, velocity: 82, start: 7.5, duration: 0.5 },
        // A1 on beat 8
        { pitch: 33, velocity: 88, start: 8, duration: 1 },
        { pitch: 40, velocity: 82, start: 8.5, duration: 0.5 },
        { pitch: 33, velocity: 88, start: 9, duration: 0.5 },
        { pitch: 40, velocity: 82, start: 9.5, duration: 0.5 },
        { pitch: 33, velocity: 88, start: 10, duration: 0.5 },
        { pitch: 40, velocity: 82, start: 10.5, duration: 0.5 },
        { pitch: 33, velocity: 88, start: 11, duration: 0.5 },
        { pitch: 40, velocity: 82, start: 11.5, duration: 0.5 },
        // F1 on beat 12
        { pitch: 29, velocity: 88, start: 12, duration: 1 },
        { pitch: 36, velocity: 82, start: 12.5, duration: 0.5 },
        { pitch: 29, velocity: 88, start: 13, duration: 0.5 },
        { pitch: 36, velocity: 82, start: 13.5, duration: 0.5 },
        { pitch: 29, velocity: 88, start: 14, duration: 0.5 },
        { pitch: 36, velocity: 82, start: 14.5, duration: 0.5 },
        { pitch: 29, velocity: 88, start: 15, duration: 0.5 },
        { pitch: 36, velocity: 82, start: 15.5, duration: 0.5 },
      ],
    },
    {
      trackIndex: 2,
      type: 'midi',
      name: 'Chord Stabs',
      startBeat: 0,
      duration: 16,
      color: '#EC4899',
      loop: true,
      notes: [
        // C major — beat 0
        { pitch: 48, velocity: 80, start: 0, duration: 1.5 },
        { pitch: 52, velocity: 76, start: 0, duration: 1.5 },
        { pitch: 55, velocity: 78, start: 0, duration: 1.5 },
        { pitch: 60, velocity: 72, start: 0, duration: 1.5 },
        // G major — beat 2
        { pitch: 43, velocity: 78, start: 2, duration: 1.5 },
        { pitch: 47, velocity: 74, start: 2, duration: 1.5 },
        { pitch: 50, velocity: 76, start: 2, duration: 1.5 },
        { pitch: 55, velocity: 70, start: 2, duration: 1.5 },
        // A minor — beat 4
        { pitch: 45, velocity: 78, start: 4, duration: 1.5 },
        { pitch: 48, velocity: 74, start: 4, duration: 1.5 },
        { pitch: 52, velocity: 76, start: 4, duration: 1.5 },
        { pitch: 57, velocity: 70, start: 4, duration: 1.5 },
        // F major — beat 6
        { pitch: 41, velocity: 78, start: 6, duration: 1.5 },
        { pitch: 45, velocity: 74, start: 6, duration: 1.5 },
        { pitch: 48, velocity: 76, start: 6, duration: 1.5 },
        { pitch: 53, velocity: 70, start: 6, duration: 1.5 },
        // repeat
        { pitch: 48, velocity: 80, start: 8, duration: 1.5 },
        { pitch: 52, velocity: 76, start: 8, duration: 1.5 },
        { pitch: 55, velocity: 78, start: 8, duration: 1.5 },
        { pitch: 60, velocity: 72, start: 8, duration: 1.5 },
        { pitch: 43, velocity: 78, start: 10, duration: 1.5 },
        { pitch: 47, velocity: 74, start: 10, duration: 1.5 },
        { pitch: 50, velocity: 76, start: 10, duration: 1.5 },
        { pitch: 55, velocity: 70, start: 10, duration: 1.5 },
        { pitch: 45, velocity: 78, start: 12, duration: 1.5 },
        { pitch: 48, velocity: 74, start: 12, duration: 1.5 },
        { pitch: 52, velocity: 76, start: 12, duration: 1.5 },
        { pitch: 57, velocity: 70, start: 12, duration: 1.5 },
        { pitch: 41, velocity: 78, start: 14, duration: 1.5 },
        { pitch: 45, velocity: 74, start: 14, duration: 1.5 },
        { pitch: 48, velocity: 76, start: 14, duration: 1.5 },
        { pitch: 53, velocity: 70, start: 14, duration: 1.5 },
      ],
    },
    {
      trackIndex: 3,
      type: 'audio',
      name: 'Riser',
      startBeat: 12,
      duration: 4,
      color: '#10B981',
      fileUrl: '/audio/templates/edm/riser.wav',
      loop: false,
    },
  ],
};
