import { ProjectTemplate } from './types';

export const hiphopTemplate: ProjectTemplate = {
  id: 'hip-hop',
  name: 'Hip-Hop Drums',
  description: '808 kick, clap, hi-hat pattern. Add your own melody.',
  category: 'Beat Making',
  genre: 'Hip-Hop',
  difficulty: 'Beginner',
  bpm: 90,
  timeSignature: '4/4',
  keySignature: 'C minor',
  accentColor: '#f59e0b',
  previewIcon: '🥁',
  tracks: [
    {
      name: '808 Kick',
      type: 'drummer',
      color: '#f59e0b',
      volume: 0.85,
      pan: 0,
      muted: false,
      soloed: false,
      icon: 'drum',
    },
    {
      name: 'Clap',
      type: 'drummer',
      color: '#f97316',
      volume: 0.7,
      pan: 0,
      muted: false,
      soloed: false,
      icon: 'drum',
    },
    {
      name: 'Hi-Hat',
      type: 'drummer',
      color: '#84cc16',
      volume: 0.55,
      pan: 0.2,
      muted: false,
      soloed: false,
      icon: 'drum',
    },
    {
      name: '808 Bass',
      type: 'instrument',
      instrument: 'synth-bass',
      color: '#a855f7',
      volume: 0.8,
      pan: 0,
      muted: false,
      soloed: false,
      icon: 'music',
    },
  ],
  clips: [
    {
      trackIndex: 0,
      type: 'midi',
      name: 'Kick Pattern',
      startBeat: 0,
      duration: 8,
      color: '#f59e0b',
      notes: [
        { pitch: 36, velocity: 110, start: 0, duration: 0.5 },
        { pitch: 36, velocity: 110, start: 2, duration: 0.5 },
        { pitch: 36, velocity: 120, start: 4, duration: 0.5 },
        { pitch: 36, velocity: 100, start: 6, duration: 0.5 },
        { pitch: 36, velocity: 110, start: 7, duration: 0.5 },
      ],
    },
    {
      trackIndex: 1,
      type: 'midi',
      name: 'Clap Pattern',
      startBeat: 0,
      duration: 8,
      color: '#f97316',
      notes: [
        { pitch: 38, velocity: 100, start: 1, duration: 0.5 },
        { pitch: 38, velocity: 100, start: 3, duration: 0.5 },
        { pitch: 38, velocity: 100, start: 5, duration: 0.5 },
        { pitch: 38, velocity: 110, start: 7, duration: 0.5 },
      ],
    },
    {
      trackIndex: 2,
      type: 'midi',
      name: 'Hi-Hat Pattern',
      startBeat: 0,
      duration: 8,
      color: '#84cc16',
      notes: [
        { pitch: 42, velocity: 80, start: 0, duration: 0.25 },
        { pitch: 42, velocity: 60, start: 0.5, duration: 0.25 },
        { pitch: 42, velocity: 80, start: 1, duration: 0.25 },
        { pitch: 42, velocity: 60, start: 1.5, duration: 0.25 },
        { pitch: 42, velocity: 80, start: 2, duration: 0.25 },
        { pitch: 42, velocity: 60, start: 2.5, duration: 0.25 },
        { pitch: 42, velocity: 80, start: 3, duration: 0.25 },
        { pitch: 42, velocity: 60, start: 3.5, duration: 0.25 },
        { pitch: 42, velocity: 80, start: 4, duration: 0.25 },
        { pitch: 42, velocity: 70, start: 4.5, duration: 0.25 },
        { pitch: 42, velocity: 80, start: 5, duration: 0.25 },
        { pitch: 42, velocity: 60, start: 5.5, duration: 0.25 },
        { pitch: 42, velocity: 80, start: 6, duration: 0.25 },
        { pitch: 42, velocity: 60, start: 6.5, duration: 0.25 },
        { pitch: 42, velocity: 90, start: 7, duration: 0.25 },
        { pitch: 42, velocity: 70, start: 7.5, duration: 0.25 },
      ],
    },
    {
      trackIndex: 3,
      type: 'midi',
      name: '808 Bass',
      startBeat: 0,
      duration: 8,
      color: '#a855f7',
      notes: [
        { pitch: 36, velocity: 100, start: 0, duration: 1.5 },
        { pitch: 36, velocity: 100, start: 2, duration: 0.5 },
        { pitch: 43, velocity: 100, start: 3, duration: 0.5 },
        { pitch: 36, velocity: 100, start: 4, duration: 1.5 },
        { pitch: 38, velocity: 100, start: 6, duration: 0.5 },
        { pitch: 43, velocity: 100, start: 7, duration: 0.5 },
      ],
    },
  ],
};
