import { ProjectTemplate } from './types';

export const lofiTemplate: ProjectTemplate = {
  id: 'lofi-beat',
  name: 'Lo-fi Beat',
  description: 'Warm chill groove with soft piano and dusty drums',
  category: 'Music',
  genre: 'Lo-fi Hip Hop',
  difficulty: 'Beginner',
  bpm: 78,
  timeSignature: '4/4',
  keySignature: 'C Major',
  accentColor: '#8B5CF6',
  previewIcon: '🎹',
  tracks: [
    {
      name: 'Drums',
      type: 'audio',
      color: '#F59E0B',
      volume: 0.75,
      pan: 0,
      muted: false,
      soloed: false,
      icon: 'drum',
      outputBusId: 'stereo-out',
    },
    {
      name: 'Piano',
      type: 'instrument',
      instrument: 'Steinway Piano',
      color: '#8B5CF6',
      volume: 0.7,
      pan: -0.1,
      muted: false,
      soloed: false,
      icon: 'keyboard',
      outputBusId: 'stereo-out',
    },
    {
      name: 'Atmosphere',
      type: 'audio',
      color: '#10B981',
      volume: 0.35,
      pan: 0.15,
      muted: false,
      soloed: false,
      icon: 'mic',
      outputBusId: 'stereo-out',
    },
  ],
  clips: [
    {
      trackIndex: 0,
      type: 'audio',
      name: 'Lo-fi Drums',
      startBeat: 0,
      duration: 16,
      color: '#F59E0B',
      fileUrl: '/audio/templates/lofi/drums.wav',
      loop: true,
    },
    {
      trackIndex: 1,
      type: 'midi',
      name: 'Soft Piano',
      startBeat: 0,
      duration: 16,
      color: '#8B5CF6',
      loop: true,
      notes: [
        // Cmaj7 — beat 0
        { pitch: 60, velocity: 72, start: 0, duration: 4 },
        { pitch: 64, velocity: 65, start: 0, duration: 4 },
        { pitch: 67, velocity: 68, start: 0, duration: 4 },
        { pitch: 71, velocity: 60, start: 0, duration: 4 },
        // Am7 — beat 4
        { pitch: 57, velocity: 70, start: 4, duration: 4 },
        { pitch: 60, velocity: 63, start: 4, duration: 4 },
        { pitch: 64, velocity: 66, start: 4, duration: 4 },
        { pitch: 67, velocity: 58, start: 4, duration: 4 },
        // Dm7 — beat 8
        { pitch: 62, velocity: 68, start: 8, duration: 4 },
        { pitch: 65, velocity: 62, start: 8, duration: 4 },
        { pitch: 69, velocity: 64, start: 8, duration: 4 },
        { pitch: 72, velocity: 56, start: 8, duration: 4 },
        // G7 — beat 12
        { pitch: 55, velocity: 66, start: 12, duration: 4 },
        { pitch: 59, velocity: 60, start: 12, duration: 4 },
        { pitch: 62, velocity: 62, start: 12, duration: 4 },
        { pitch: 65, velocity: 54, start: 12, duration: 4 },
      ],
    },
    {
      trackIndex: 2,
      type: 'audio',
      name: 'Warm Pad',
      startBeat: 0,
      duration: 16,
      color: '#10B981',
      fileUrl: '/audio/templates/lofi/atmosphere.wav',
      loop: true,
    },
  ],
};
