/**
 * sf2Presets.cjs
 * Read the preset list out of a SoundFont, with no dependencies.
 *
 * This is a second, deliberately minimal implementation of something
 * `engine/instruments/soundfont/SoundFontParser.ts` already does. It exists
 * because the manifest is generated by a build script that runs before any
 * TypeScript is compiled, so it cannot import the engine.
 *
 * Two implementations of the same thing is a drift risk, and here drift would
 * be expensive: `presetIndex` is stored in saved projects, so if the two
 * disagreed about ordering every instrument in every project would silently
 * change. `tests/smoke/soundfontManifest.test.ts` runs both over the same bytes
 * and asserts they agree, which is what makes the duplication safe.
 *
 * Only `phdr` is read. Zones, generators and samples do not affect a preset
 * list, and leaving them out is what keeps this small enough to trust.
 *
 * CommonJS rather than ESM so Jest can require it directly — it always treats
 * `.mjs` as an ES module, which would mean running the whole suite under
 * `--experimental-vm-modules` for this one file. Node's ESM loader detects the
 * named exports below, so the build script still imports it normally.
 */

const PHDR_RECORD_BYTES = 38;

/** Read a four-character chunk id. */
function readFourCC(view, offset) {
    return String.fromCharCode(
        view.getUint8(offset),
        view.getUint8(offset + 1),
        view.getUint8(offset + 2),
        view.getUint8(offset + 3),
    );
}

/**
 * Find a subchunk inside the `pdta` LIST.
 *
 * RIFF nests: the file is `RIFF <size> sfbk`, then a series of
 * `LIST <size> <type>` chunks each holding subchunks. Preset headers live in
 * the `phdr` subchunk of the `pdta` list.
 *
 * Returns the offset of the chunk's *data* and its size, or null.
 */
function findPdtaChunk(view, wanted) {
    if (readFourCC(view, 0) !== 'RIFF' || readFourCC(view, 8) !== 'sfbk') {
        throw new Error('not a SoundFont (missing RIFF/sfbk header)');
    }

    const end = Math.min(view.byteLength, 8 + view.getUint32(4, true));
    let p = 12;

    while (p + 8 <= end) {
        const id = readFourCC(view, p);
        const size = view.getUint32(p + 4, true);

        if (id === 'LIST' && p + 12 <= end && readFourCC(view, p + 8) === 'pdta') {
            const listEnd = Math.min(end, p + 8 + size);
            let q = p + 12;

            while (q + 8 <= listEnd) {
                const subId = readFourCC(view, q);
                const subSize = view.getUint32(q + 4, true);
                if (subId === wanted) return { offset: q + 8, size: subSize };
                // Chunks are word-aligned: an odd size is followed by a pad byte.
                q += 8 + subSize + (subSize % 2);
            }
        }

        p += 8 + size + (size % 2);
    }

    return null;
}

/**
 * Every preset in the font, in `phdr` order.
 *
 * The order is the contract: `SoundFontParser` pushes presets in the same order
 * without sorting, and `presetIndex` indexes that array.
 */
function extractPresets(buffer) {
    const view = new DataView(buffer);
    const phdr = findPdtaChunk(view, 'phdr');
    if (!phdr) throw new Error('no phdr chunk');

    // The last record is the terminal EOP marker, not a preset. Dropping it is
    // the same `count - 1` the engine's parser applies.
    const count = Math.floor(phdr.size / PHDR_RECORD_BYTES) - 1;
    if (count <= 0) throw new Error('phdr contains no presets');

    const presets = [];
    for (let i = 0; i < count; i++) {
        const at = phdr.offset + i * PHDR_RECORD_BYTES;

        let name = '';
        for (let c = 0; c < 20; c++) {
            const code = view.getUint8(at + c);
            if (code === 0) break;
            name += String.fromCharCode(code);
        }

        presets.push({
            index: i,
            name: name.trim(),
            bank: view.getUint16(at + 22, true),
            program: view.getUint16(at + 20, true),
        });
    }

    return presets;
}

module.exports = { findPdtaChunk, extractPresets };
